// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {engine} from '../models';
import {context} from '../models';

export function ApplyFiltersAlgoOpt(arg1:main.ApplyRequest):Promise<main.ApplyResultEx>;

export function EnsureMyKeysAndSamples():Promise<void>;

export function GetCurrentKeyName():Promise<string>;

export function GetHelpImage(arg1:string):Promise<string>;

export function GetMatrix():Promise<engine.Matrix>;

export function ListMyKeys():Promise<Array<main.KeyInfo>>;

export function PickKey(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
