// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyFiltersAlgoOpt(arg1) {
  return window['go']['main']['App']['ApplyFiltersAlgoOpt'](arg1);
}

export function EnsureMyKeysAndSamples() {
  return window['go']['main']['App']['EnsureMyKeysAndSamples']();
}

export function GetCurrentKeyName() {
  return window['go']['main']['App']['GetCurrentKeyName']();
}

export function GetHelpImage(arg1) {
  return window['go']['main']['App']['GetHelpImage'](arg1);
}

export function GetMatrix() {
  return window['go']['main']['App']['GetMatrix']();
}

export function ListMyKeys() {
  return window['go']['main']['App']['ListMyKeys']();
}

export function PickKey(arg1) {
  return window['go']['main']['App']['PickKey'](arg1);
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}
